language: java

install :
 - mvn install
 - mvn sonar:sonar \
  -SONAR_PROJECT_KEY=HeyChef_Ecommerce \
  -SONAR_ORGANIZATION=heychef-github \
  -SONAR_HOST=https://sonarcloud.io \
  -SONAR_LOGIN=b1af5715c8497426b32d0b8fbeaadef69649c536
